### ISSUE TITLE
Why not use the .twig extension for views?

### ISSUE THREAD

**Issue by hayatbiralem** [florianbouvot/aperitif#1]
Hi,

I like Twig too and most IDEs support its beautiful syntax if you use correct extension.

And [gulp-twig](https://github.com/zimmen/gulp-twig) converts `*.twig` files to `*.html` files automatically.

Do you have a specific reason to use the `.html` extension?

![image](https://cloud.githubusercontent.com/assets/2085468/19105082/cf759b46-8ae8-11e6-8e32-2c12b915ac47.png)

**Comment by florianbouvot** [comment]
@hayatbiralem good point, I didn't switch to `*.twig` extension because I currently work with Coda 2 and there is some issue with autocompletion.

*But my coworker use PHPStorm and everything work well with `*.twig`extension.*

Any IDE advice ?

**Comment by hayatbiralem** [comment]
@florianbouvot I would strongly recommend PhpStorm and I am a Front-End Developer. My coworker is using PhpStorm too and that's why I start using PhpStorm.

I've never used before WebStorm but I was curious and I found [this link](http://stackoverflow.com/questions/25647004/difference-between-webstorm-and-phpstorm). Apparently no significant difference.

I've never used before Coda too so I don't know what the expectations but I'm quite pleased PhpStorm.

Also a new popular IDE is there: [Atom](https://atom.io/). I plan to try it.

I hope you find what works best for you.

**Comment by florianbouvot** [comment]
@hayatbiralem I have quickly try both (PhpStorm and Atom). 

* PhpStorm seems powerful but a little too "big"
* Atom is cool but autocompletion is limited
* Coda is in between but need a major update

**Comment by hayatbiralem** [comment]
I agree with that. It is big but I think it can be ignored.

I understand that you want to continue with the Coda and it is quite reasonable. I hope they release the update soon.

**Comment by florianbouvot** [comment]
Next major release of Coda is for 2017. I have time to try PhpStrom...

**Comment by hayatbiralem** [comment]
Nice! I'm glad to hear that! Sorry :)

**Comment by florianbouvot** [comment]
@hayatbiralem I'm steal using `.html` extension by default because of Coda but I add support for `.twig` extension 😄

**Comment by hayatbiralem** [comment]
Neat 👍 😉
